language: python
python:
  - "3.8"
  - "3.9"
  - "3.10"
  - "3.11"
  - "3.12.1"

install:
  - pip install -r requirements.txt
  - pip install coverage==4.3 #codeclimate test reporter does not work with 4.0
  - pip install pytest
  - pip install pytest-cov
  - pip install codeclimate-test-reporter


script:
  - pytest --cov=src

after_success:
  - codeclimate-test-reporter --file .coverage
